name    'ghoneycutt-sendmail'
version '0.0.1'
source 'UNKNOWN'
author 'herffjones'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

dependency 'ghoneycutt/postfix', '= 0.0.1'
